services:
  postgres:
    image: postgres:16
    container_name: postgres16_em
    restart: always
    env_file:
      - blog_app/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: blog_app/Dockerfile
    restart: always
    env_file:
      - blog_app/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7-alpine
    container_name: fastapi_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - blog_app/.env
    command:
      - sh
      - -c
      - 'exec redis-server --appendonly yes --requirepass "$$REDIS_PASSWORD"'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_selectel
    restart: always
    env_file:
      - blog_app/.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  redis_data:
  pgdata: